name: run-test
permissions:
  contents: read

on:
  pull_request:

jobs:
  list-tests:
    runs-on: ubuntu-latest
    outputs:
      tests: ${{ steps.list-tests.outputs.tests }}
    steps:
      - name: Check out gnoswap repo
        uses: actions/checkout@v4

      - name: List integration tests
        id: list-tests
        run: |
          tests=$(find tests/integration/testdata -name "*.txtar" -type f | \
            sed 's|tests/integration/testdata/||' | \
            sed 's|/|_|g' | \
            sed 's|\.txtar||' | \
            jq -R -s -c 'split("\n")[:-1]')
          echo "tests=$tests" >> $GITHUB_OUTPUT

  run-integration-test:
    needs: list-tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test: ${{ fromJson(needs.list-tests.outputs.tests) }}

    steps:
      - name: Check out gnoswap repo
        uses: actions/checkout@v4

      - name: Check out gno
        uses: actions/checkout@v4
        with:
          repository: gnoswap-labs/gno
          ref: master
          path: ./gno

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Run setup.py
        run: |
          python3 setup.py --exclude-tests -w .

      - name: Run integration test - ${{ matrix.test }}
        run: |
          cd gno/gno.land/pkg/integration
          go test -v . -run TestTestdata/${{ matrix.test }}
